name: pagocrypto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  go_router: ^14.0.0
  shared_preferences: ^2.0.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.0
  http: ^1.0.0
  flutter_svg: ^2.0.0
  google_fonts: ^6.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # Aptos font configuration
  # Note: Font files need to be added to assets/fonts/ directory
  # Download Aptos font files (.ttf) and place them in assets/fonts/
  # fonts:
  #   - family: Aptos
  #     fonts:
  #       - asset: assets/fonts/Aptos-Regular.ttf
  #       - asset: assets/fonts/Aptos-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Aptos-Italic.ttf
  #         style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon3.png"
  min_sdk_android: 21
  remove_alpha_ios: true
